### ISSUE TITLE
Inconsistent layout of overview page

### ISSUE THREAD

**Issue by t-schroeder** [Opencast-Moodle/moodle-block_opencast#71]
A while ago this CSS rule was introduced to the boost theme:
```scss
// Minimum height required for a menu in a table inside a scrollable div.
.no-overflow > .generaltable {
    margin-bottom: 0;
    min-height: 10em;
}
```

But that CSS rule only applies to one of the two tables on the overview page:
![min-height](https://user-images.githubusercontent.com/24255259/46287460-daad2200-c582-11e8-9cbe-fec2253cfda4.PNG)

In my opinion the two tables should either both have the `min-height` or none of them should have it.
